# Generated by Django 3.1.3 on 2021-01-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Multiple_model', '0002_maindetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainDetails',
        ),
    ]
