# Generated by Django 3.1.3 on 2020-12-31 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainWhoWeAre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_english', models.CharField(max_length=200)),
                ('page_template_english', models.CharField(max_length=200)),
                ('page_heading_english', models.CharField(max_length=200)),
                ('our_story', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='Multiple_Nested_serializer.ourstory')),
            ],
        ),
    ]
