# Generated by Django 3.1.3 on 2021-01-03 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Multiple_Nested_serializer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ourservice_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='our_service_image')),
                ('image_sd', models.ImageField(upload_to='ourservice_sd')),
            ],
        ),
        migrations.RemoveField(
            model_name='mainwhoweare',
            name='page_template_english',
        ),
        migrations.RemoveField(
            model_name='mainwhoweare',
            name='page_title_english',
        ),
        migrations.AlterField(
            model_name='mainwhoweare',
            name='our_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoryBy', to='Multiple_Nested_serializer.ourstory'),
        ),
        migrations.AddField(
            model_name='mainwhoweare',
            name='our_service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serviceBy', to='Multiple_Nested_serializer.ourservice'),
            preserve_default=False,
        ),
    ]
